### ISSUE TITLE
Wyszukiwanie pokoju po liczbie gości

### ISSUE THREAD

**Issue by nowakprojects** [nowakprojects/CodersCamp2019.Projekt4.NodeJS-REST#6]
- [ ] W RoomServiceSearch.ts stworzę funkcję dla wszystkich zadań zw. z wyszukiwaniem (#6, #7, #8, #9 , #10). Będzie przyjmować jako argument obiekt z numberOfGuests, additionalServices, minPrice, maxPrice, minAverageRating, location, maxDistanceFromTheCenter (tu jeszcze nie jestem pewna)

- [ ] Stworzę interfejs ze wszystkimi wystawionymi ofertami

- [ ] Napiszę kwerendę

- [ ] Funkcja zwróci wybrane oferty

**Comment by ewzdun** [comment]
- [ ] W RoomServiceSearch.ts stworzę funkcję dla wszystkich zadań zw. z wyszukiwaniem (#6, #7, #8, #9 , #10). Będzie przyjmować argumenty - numberOfGuests, additionalServices, minPrice, maxPrice, minAverageRating, location, maxDistanceFromTheCenter (tu jeszcze nie jestem pewna)

- [ ] Napiszę kwerendę, uwzględniając parametry
Tutaj mam zasadniczy problem, bo nie wiem, gdzie wszystkie możliwe oferty będą. Nie wiem, na czym wykonywać .find .select itd

- [ ] Funkcja zwróci tylko id wybranych ofert (znając id będziemy mogli później je wyświetlić)

**Comment by nowakprojects** [comment]
@ewzdun Możesz edytować opis taska :) ? Bo byłoby dobrze umieścić tam te korki

Ad. 1 - dobrze jakby argumenty były w jakimś jedynm obiekcie - wszystkie opcjonalne
Ad. 2 - Po to są interfejsy. Zrób interfejs w stylu UserProfileRepository - zaimplementuj w pamięci (zobacz InMemoryUserProfileRepository). Kiedy @AniaDM wykona część z zamieszczaniem ofert, wtedy podmieni się implementację na łączącą się z zamieszczonymi ofertami. Dlatego używamy TypeScript - żeby był taki zabieg możliwy. I tak się zazwyczaj robi :) Określamy sobie tzw. "kontrakt" czyli czego oczekujemy - wykonujemy implementacje w pamieci, a potem najwyzej dostosowujemy. 
Ad. 3 - Proponuję zwrócić dane, które będziemy chcieli wyświetlić :) Nie ma po co potem wyszukiwać. Chyba, że widzisz jakieś plusy?

@ewzdun  Zrozumiałaś punkt 2?

**Comment by ewzdun** [comment]
ad. 2 chyba zrozumiałam :D 
ad. 3 nie widzę, pewnie zauważyłabym minusy później ;P
Dzięki!
